language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn coverage
after-script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
